데이터베이스 구축을 위한 Docker 구성
98OO/colla-backend pull request #11
Opened 2024-04-13 15:37 UTC by Seol-JY

## 📌 관련 이슈

- closed: https://github.com/98OO/colla-backend/issues/9

## ✨ PR 세부 내용
**개발 환경 및 프로덕션 환경에서 사용할 데이터베이스들을 도커라이징 합니다.**
- MySQL 볼륨 파일 gitignore에 등록
- MySQL 구성을 위한 Docker Compose 파일 작성
- Redis 구성을 위한 Docker Compose 파일 작성
- 정상 Compose Up 작동 확인

<br/>

**Docker Compose 실행 방법**
실행 전 환경변수 지정 필요
```shell
cd docker
MYSQL_HOST_PORT={} MYSQL_ROOT_PASSWORD="{}" MYSQL_USER="{}" MYSQL_PASSWORD="{}" REDIS_HOST_PORT={} docker-compose up -d
```
전체 명령어는 프로젝트 Notion에 명시해 두었습니다.

2024-04-13 15:42 UTC, Junad-Park requested changes

2024-04-13 15:42 UTC, Junad-Park commented on .gitignore
> +##### docker ###
p2) 앞부분에 #이 5개 있습니다!  3개로 바꾸는게 어떨까요?

2024-04-13 15:47 UTC, Seol-JY commented on .gitignore
> +##### docker ###
@Junad-Park 수정했습니다!

2024-04-13 15:49 UTC, Junad-Park approved these changes

2024-04-13 16:03 UTC, merged

2024-04-13 16:13 UTC, Seol-JY commented
커멘트 테스트

2024-04-15 00:39 UTC, Seol-JY commented
test

2024-04-15 00:41 UTC, Seol-JY commented on docker/docker-compose.yml
> +    ports:
test